# ==========================================
#          GuiSell Configuration
#          Created by KryonT/zainim0
# ==========================================

settings:
  # The title of the GUI when players open it
  gui-title: "&b&lSnowy&f&lSMP &8» &3Drop items"

messages:
  # The message sent to players after they close the GUI
  sell-success: "&b&lSNOWY &8» &7You earned &f$%amount% &7coins!"
  
  # The message sent if someone without permission tries to use it
  no-permission: "&b&lSNOWY &8» &cYou don't have permission to sell here."